#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.10.0
# Generated On: 2/17/2013 4:22 PM
# Generated By: HP_Administrator
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$label2 = New-Object System.Windows.Forms.Label
$label1 = New-Object System.Windows.Forms.Label
$txtLastIP = New-Object System.Windows.Forms.TextBox
$txtFirstIP = New-Object System.Windows.Forms.TextBox
$txtNetworkName = New-Object System.Windows.Forms.TextBox
$btnCancel = New-Object System.Windows.Forms.Button
$btnOK = New-Object System.Windows.Forms.Button
$lblPrompt = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$GetData= 
{
#TODO: Place custom script here
$form1.DialogResult="OK"
$form1.Close()

$n = $txtNetworkName.text
$s = [int]$txtFirstIP.text
$l = [int]$txtLastIP.text
$sint = [int]$txtFirstIP.text


if(test-path c:\scripts\pingresults.txt)
{  remove-item c:\scripts\pingresults.txt
}

do {
try
{
$results = test-connection $n$sint -count 1 -buffersize 16 -erroraction stop
write-host "SUCCESSFUL: $n$sint" 
"SUCCESSFUL: $n$sint"| out-file c:\scripts\pingresults.txt -append

}
catch
{
write-host "$n$sint is UNREACHABLE." 
"
$n$sint is unreachable
" | out-file c:\scripts\pingresults.txt -append
}
finally
{
$sint++
}
}
while ($sint -le $l)
notepad c:\scripts\pingresults.txt
}

$handler_lblPrompt_Click= 
{
#TODO: Place custom script here

}

$Cancel= 
{ 
$form1.DialogResult="Cancel"
$form1.Close()
#TODO: Place custom script here

}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 178
$System_Drawing_Size.Width = 234
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Ping Range"

$label2.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 90
$label2.Location = $System_Drawing_Point
$label2.Name = "label2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 74
$label2.Size = $System_Drawing_Size
$label2.TabIndex = 7
$label2.Text = "Last IP"
$label2.TextAlign = 64

$form1.Controls.Add($label2)

$label1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 5
$System_Drawing_Point.Y = 63
$label1.Location = $System_Drawing_Point
$label1.Name = "label1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 83
$label1.Size = $System_Drawing_Size
$label1.TabIndex = 6
$label1.Text = "First IP"
$label1.TextAlign = 64

$form1.Controls.Add($label1)

$txtLastIP.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 93
$System_Drawing_Point.Y = 89
$txtLastIP.Location = $System_Drawing_Point
$txtLastIP.Name = "txtLastIP"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txtLastIP.Size = $System_Drawing_Size
$txtLastIP.TabIndex = 5
$txtLastIP.Text = "110"

$form1.Controls.Add($txtLastIP)

$txtFirstIP.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 93
$System_Drawing_Point.Y = 63
$txtFirstIP.Location = $System_Drawing_Point
$txtFirstIP.Name = "txtFirstIP"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txtFirstIP.Size = $System_Drawing_Size
$txtFirstIP.TabIndex = 4
$txtFirstIP.Text = "100"

$form1.Controls.Add($txtFirstIP)

$txtNetworkName.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 93
$System_Drawing_Point.Y = 36
$txtNetworkName.Location = $System_Drawing_Point
$txtNetworkName.Name = "txtNetworkName"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 100
$txtNetworkName.Size = $System_Drawing_Size
$txtNetworkName.TabIndex = 3
$txtNetworkName.Text = "192.168.1."

$form1.Controls.Add($txtNetworkName)


$btnCancel.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 118
$System_Drawing_Point.Y = 132
$btnCancel.Location = $System_Drawing_Point
$btnCancel.Name = "btnCancel"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$btnCancel.Size = $System_Drawing_Size
$btnCancel.TabIndex = 2
$btnCancel.Text = "Cancel"
$btnCancel.UseVisualStyleBackColor = $True
$btnCancel.add_Click($Cancel)

$form1.Controls.Add($btnCancel)


$btnOK.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 13
$System_Drawing_Point.Y = 132
$btnOK.Location = $System_Drawing_Point
$btnOK.Name = "btnOK"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$btnOK.Size = $System_Drawing_Size
$btnOK.TabIndex = 1
$btnOK.Text = "OK"
$btnOK.UseVisualStyleBackColor = $True
$btnOK.add_Click($GetData)

$form1.Controls.Add($btnOK)

$lblPrompt.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 5
$System_Drawing_Point.Y = 33
$lblPrompt.Location = $System_Drawing_Point
$lblPrompt.Name = "lblPrompt"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 83
$lblPrompt.Size = $System_Drawing_Size
$lblPrompt.TabIndex = 0
$lblPrompt.Text = "Base IP"
$lblPrompt.TextAlign = 64
$lblPrompt.add_Click($handler_lblPrompt_Click)

$form1.Controls.Add($lblPrompt)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm






