## Aliases ##
Set-Alias key Get-Key
Set-Alias assist Get-RemoteConnection
Set-Alias unlock Unlock-aduser
Set-Alias findu Find-ADUser
Set-Alias findc Find-ADComputer
Set-Alias Out-Clipboard clip
Set-Alias helpdesk Launch-Helpdesk
Set-Alias cal Output-Calendar
Set-Alias lsc Color-LS
Set-Alias cping Ping-Constant
Set-Alias sd Stop-Computer
Set-Alias Sync Sync-Files
Set-Alias ssh Enter-SSHSession
Set-Alias clone Enter-Clonezilla
Set-Alias lastboot Get-LastBootTime
Set-Alias grep Select-String
Set-Alias rn Rename-Item
Set-Alias fsize Get-FolderSize
Set-Alias wttr Get-WeatherPicture
Set-Alias ifconfig Get-IPInfo
Set-Alias week Get-WeekOfYear
Set-Alias reboot Restart-Computer
Set-Alias kickoff Disconnect-CurrentUser
Set-Alias kitrix Disconnect-CitrixSession
Set-Alias arch Search-ArchWiki
Set-Alias wiki Search-MISWiki
Set-Alias touch new-item
Set-Alias bible Get-BibleVerse

# Launcher Aliases #
Set-Alias anasazi Launch-Anasazi
Set-Alias inventory Launch-AssetInventory
Set-Alias paylocity Launch-Paylocity
Set-Alias far Launch-Far
Set-Alias np notepad
Set-Alias san Manage-EqualLogic
Set-Alias video Launch-Video
Set-Alias youtube Search-YouTube
Set-Alias tools Select-AdministrativeTool
Set-Alias screen Start-ScreenConnect
Set-alias crd Launch-ChromeRemoteDesktop
Set-Alias cmbhs Launch-CMBHS
Set-Alias dell Launch-DellSupport
Set-Alias wayne SSH-Wayne
Set-Alias countdown Get-ClosingTime
Set-Alias share Launch-SharePoint
Set-Alias mis Launch-MISSharePoint
Set-Alias visualtime Launch-VisualTime
